//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeCareCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgeCareCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 1.
        /// </summary>
        internal static string BPN1 {
            get {
                return ResourceManager.GetString("BPN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 2.
        /// </summary>
        internal static string BPN2 {
            get {
                return ResourceManager.GetString("BPN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 3.
        /// </summary>
        internal static string BPN3 {
            get {
                return ResourceManager.GetString("BPN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 4.
        /// </summary>
        internal static string BPN4 {
            get {
                return ResourceManager.GetString("BPN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Care.
        /// </summary>
        internal static string BridgeCare {
            get {
                return ResourceManager.GetString("BridgeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Total.
        /// </summary>
        internal static string BridgeTotal {
            get {
                return ResourceManager.GetString("BridgeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS Condition By Bridge Count.
        /// </summary>
        internal static string CombineNHSNonNHSConditionByBridgeCount {
            get {
                return ResourceManager.GetString("CombineNHSNonNHSConditionByBridgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS Without Committed Projects
        ///Combine NHS and Non-NHS Without Committed Projects
        ///Condition By Deck Area.
        /// </summary>
        internal static string CombineNHSNonNHSConditionByDeckArea {
            get {
                return ResourceManager.GetString("CombineNHSNonNHSConditionByDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed Total.
        /// </summary>
        internal static string CommittedTotal {
            get {
                return ResourceManager.GetString("CommittedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULV_DURATION_N.
        /// </summary>
        internal static string CulvDurationN {
            get {
                return ResourceManager.GetString("CulvDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to culvert.
        /// </summary>
        internal static string Culvert {
            get {
                return ResourceManager.GetString("Culvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culvert Total.
        /// </summary>
        internal static string CulvertTotal {
            get {
                return ResourceManager.GetString("CulvertTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULV_SEEDED.
        /// </summary>
        internal static string CulvSeeded {
            get {
                return ResourceManager.GetString("CulvSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECK_DURATION_N.
        /// </summary>
        internal static string DeckDurationN {
            get {
                return ResourceManager.GetString("DeckDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECK_SEEDED.
        /// </summary>
        internal static string DeckSeeded {
            get {
                return ResourceManager.GetString("DeckSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        internal static string Fair {
            get {
                return ResourceManager.GetString("Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Condition By Bridge Count.
        /// </summary>
        internal static string NHSConditionByBridgeCountLLCC {
            get {
                return ResourceManager.GetString("NHSConditionByBridgeCountLLCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Condition By Deck Area.
        /// </summary>
        internal static string NHSConditionByDeckAreaLLCC {
            get {
                return ResourceManager.GetString("NHSConditionByDeckAreaLLCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-NHS Condition By Bridge Count.
        /// </summary>
        internal static string NonNHSConditionByBridgeCount {
            get {
                return ResourceManager.GetString("NonNHSConditionByBridgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-NHS Condition By Deck Area.
        /// </summary>
        internal static string NonNHSConditionByDeckArea {
            get {
                return ResourceManager.GetString("NonNHSConditionByDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no treatment.
        /// </summary>
        internal static string NoTreatment {
            get {
                return ResourceManager.GetString("NoTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Budget Spent BAMS.
        /// </summary>
        internal static string PercentBudgetSpentBAMS {
            get {
                return ResourceManager.GetString("PercentBudgetSpentBAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Budget Spent MPMS.
        /// </summary>
        internal static string PercentBudgetSpentMPMS {
            get {
                return ResourceManager.GetString("PercentBudgetSpentMPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string Poor {
            get {
                return ResourceManager.GetString("Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Bridge Compare Bridge Count.
        /// </summary>
        internal static string PoorBridgeCompareBridgeCount {
            get {
                return ResourceManager.GetString("PoorBridgeCompareBridgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Bridge Compare Deck Area.
        /// </summary>
        internal static string PoorBridgeCompareDeckArea {
            get {
                return ResourceManager.GetString("PoorBridgeCompareDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Deck Area By BPN.
        /// </summary>
        internal static string PoorDeckAreaByBPN {
            get {
                return ResourceManager.GetString("PoorDeckAreaByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Budget.
        /// </summary>
        internal static string RemainingBudget {
            get {
                return ResourceManager.GetString("RemainingBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB_DURATION_N.
        /// </summary>
        internal static string SubDurationN {
            get {
                return ResourceManager.GetString("SubDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB_SEEDED.
        /// </summary>
        internal static string SubSeeded {
            get {
                return ResourceManager.GetString("SubSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUP_DURATION_N.
        /// </summary>
        internal static string SupDurationN {
            get {
                return ResourceManager.GetString("SupDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUP_SEEDED.
        /// </summary>
        internal static string SupSeeded {
            get {
                return ResourceManager.GetString("SupSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BPN Cost.
        /// </summary>
        internal static string TotalBPNCost {
            get {
                return ResourceManager.GetString("TotalBPNCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bridge Care Budget.
        /// </summary>
        internal static string TotalBridgeCareBudget {
            get {
                return ResourceManager.GetString("TotalBridgeCareBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Spent.
        /// </summary>
        internal static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }
    }
}
